sudo: required
language: scala
scala:
- 2.11.7
services:
- docker
before_install:
- docker pull java:8u92-jdk-alpine
- wget https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.11/sbt-launch.jar
- echo 'java -Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M -jar sbt-launch.jar "$@"' > sbt.sh
script:
- "docker run -it --rm --volume=$(pwd):/src --volume=/home/travis/.ivy2:/ivy2  --volume=/home/travis/.sbt:/sbt -w /src java:8u92-jdk-alpine sh sbt.sh compile test it:test pt:test"
- ls -l
- sudo chown -R travis:travis /home/travis
- ls -l
jdk:
- oraclejdk8
env:
  matrix:
  - SBT_OPTS="-XX:PermSize=512M -XX:MaxPermSize=1024M"
notifications:
  email:
    on_success: never
    on_failure: change